[build]
  publish = "site/public"
  command = "cd site && hugo --minify --gc --themesDir ../themes --timeout 300s"
  
[build.environment]
  HUGO_VERSION = "0.86.0"
  HUGO_THEME = "techfeed-hugo"
  HUGO_BASEURL = "/"