############# English navigation ##############

# main menu

[[main]]
name = "home"
url = ""
weight = 1

[[main]]
name = "vineyard"
url = "vineyard/"
weight = 2

[[main]]
name = "plants"
url = "plants/"
weight = 3

[[main]]
name = "animals"
url = "animals/"
weight = 4

[[main]]
name = "Projects"
url = "projects/"
weight = 5

[[main]]
name = "Weather"
url = "weather/"
weight = 6


# [[main]]
# name = "Recipes"
# url = "recipes/"
# weight = 7


