############# English navigation ##############

# main menu

[[main]]
name = "home"
url = ""
weight = 1

[[main]]
name = "vineyard"
url = "vineyard/"
weight = 2

[[main]]
name = "plants"
url = "plants/"
weight = 3

[[main]]
name = "animals"
url = "animals/"
weight = 4



# dropdown menu
[[main]]
name = "More"
weight = 6
hasChildren = true

[[main]]
parent = "More"
name = "Projects"
url = "projects/"
weight = 1


[[main]]
parent = "More"
name = "Recipes"
url = "recipes/"
weight = 2

[[main]]
parent = "More"
name = "Weather"
url = "weather/"
weight = 3


