############# English navigation ##############

# main menu

[[main]]
name = "home"
url = ""
weight = 1

[[main]]
name = "vineyard"
url = "vineyard/"
weight = 2
hasChildren = true

 # dropdown item
[[main]]
parent = "vineyard"
name = "Planting"
url = "vineyard/planting"

[[main]]
name = "plants"
url = "plants/"
weight = 3

[[main]]
name = "animals"
url = "animals/"
weight = 4
