#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x"
logo_width = "150px"
# logo text will only show when logo is missing.
logo_text = "TechFeed"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "TaylorTinyFarm"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# main sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright text
copyright = "TaylorTinyFarm 2022"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# author
[author_block]
title= "Taylor Tiny Farm"
image= "images/author.jpg"
content= "Has baby Ricki arrived? <b style='color:red;font-size:1em;'>No</b>.<br><br>5-18-22 2PM No change. Bethany is focussed on birthing our country music star. Ricki Joe Taylor. <br>5-18-22 9:45AM Waters be breaking up in here. Travis found coffee. <br>5-18-22 9AM Bethany had her best night of sleep in weeks. Thanks to drugs! <br>5-18-22 6AM Epidural? Epididit. Travis didn't pass out once. <br>5-17-22 10PM Bethany had apple sauce. Travis had sugar free jello. Travis gives the jello 3 stars. <br>5-17-22 8PM We are checked in at the hospital and are in a room. <br>5-17-22 7PM Eating Chick-fil-A"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################

[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/taylortinyfarm"
